In [ ]:
#pip install pandas

Requirement already satisfied: pandas in c:\users\jorge\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jorge\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jorge\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jorge\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jorge\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\jorge\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

## Crear un .xlsx con pandas

In [2]:
import pandas as pd

NOMBRE_LLM="Llama"

# Crear dataframe con datos
data = ["normal","un poco machista","muy machista"]
df = pd.DataFrame({'Machismo': [0,5,10],
                   'Llama': data,
                   'Microsoft Phi': data})

# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter("frases_creadas_LLMs.xlsx", engine='xlsxwriter')

# Convert the dataframe to an XlsxWriter Excel object. Turn off the default
# header and index and skip one row to allow us to insert a user defined
# header.
df.to_excel(writer, sheet_name= NOMBRE_LLM, startrow=1, startcol=0, header=False, index=False) 

# Get the xlsxwriter workbook and worksheet objects.
workbook = writer.book
worksheet = writer.sheets[NOMBRE_LLM]

# Get the dimensions of the dataframe.
(max_row, max_col) = df.shape

# Create a list of column headers, to use in add_table().
column_settings = []
for header in df.columns:
    column_settings.append({'header': header})

# Add the table.
worksheet.add_table(0, 0, max_row, max_col - 1, {'columns': column_settings}) #, {'columns': column_settings}

# Make the columns wider for clarity.
worksheet.set_column(0, max_col - 1, 12)

# Close the Pandas Excel writer and output the Excel file.
writer.close()

df

   Machismo             Llama     Microsoft Phi
0         0            normal            normal
1         5  un poco machista  un poco machista
2        10      muy machista      muy machista

#### Adición de una nueva fila al dataframe

In [24]:
line = pd.DataFrame({"Machismo": 30, "Llama": "Hola1", "Microsoft Phi" : "Hola2"}, index=[len(df)])
line

   Machismo  Llama Microsoft Phi
3        30  Hola1         Hola2

In [8]:
df2 = pd.concat([df, line])
df2

   Machismo             Llama     Microsoft Phi
0         0            normal            normal
1         5  un poco machista  un poco machista
2        10      muy machista      muy machista
3        30             Hola1             Hola2

### Creación del ID de la frase/grupo

Para saber qué ID ponerle, basta con acceder al final del dataframe para hallar el ID de grupo y poner el siguiente número. El ID de frase se puede generar y guardar localmente, ya que depende del grupo en el que estés.

In [15]:
num = 133
len(str(num))
miString = ""
for i in range(0, 5-len(str(num))):
    miString += "0"
miString += str(num)
miString

'00133'

## Leer un .xlsx con pandas

### Código fecha y hora

In [3]:
import datetime
tiempo = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
print(tiempo)

2025-12-11 18:21:49

### Código creación de una nueva fila

In [4]:
NOMBRE_LLM = "meta_llama_blablabla"
SCORE = 7
FRASE = "Women are not very cool."
SESGO = "Sexism"
try:
    f = open('LLM_generated_results.xlsx')
    f.close()
except FileNotFoundError:
    tabla = pd.DataFrame()
    num = 1
else:
    try:
        tabla = pd.read_excel('LLM_generated_results.xlsx', index_col=None, sheet_name="RESULTS", dtype={'GroupID' : str, 'ID' : str})
        num = int(tabla.loc[len(tabla.index) - 1].at["GroupID"]) + 1
    except ValueError:
        tabla = pd.DataFrame()
        num = 1
tabla

Empty DataFrame
Columns: []
Index: []

In [5]:
TAMAÑO_ID = 10
groupID = ""
id = 1
sentenceID = ""
for i in range(0, TAMAÑO_ID-len(str(num))):
    groupID += "0"
groupID += str(num)
for i in range(0, TAMAÑO_ID-len(str(id))):
    sentenceID += "0"
sentenceID += str(id)
groupID

'0000000001'

In [6]:
fila = pd.DataFrame({"GroupID": groupID, "ID": sentenceID, "Sentence": FRASE, "Score": SCORE, "Bias": SESGO, "LLM": NOMBRE_LLM, "Date": datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}, index=[len(tabla)])

In [15]:
tabla = pd.concat([tabla, fila])
tabla

,GroupID,ID,Sentence,Score,Bias,LLM,Date
0,1,1,Women are not very cool.,7,Sexism,meta_llama_blablabla,2025-12-11 18:22:01
0,0000000001,0000000001,Women are not very cool.,7,Sexism,meta_llama_blablabla,2025-12-11 18:22:01
0,0000000001,0000000001,Women are not very cool.,7,Sexism,meta_llama_blablabla,2025-12-11 18:22:01
0,0000000001,0000000001,Women are not very cool.,7,Sexism,meta_llama_blablabla,2025-12-11 18:22:01

In [16]:
##meter esto en una función maybe, y el writer y los parámetros se pueden crear globalmente y cerrar solo al final para agilizar el código
writer = pd.ExcelWriter("LLM_generated_results.xlsx", engine='xlsxwriter')
tabla.to_excel(writer, sheet_name= "RESULTS", startrow=1, startcol=0, header=False, index=False)
workbook = writer.book
worksheet = writer.sheets["RESULTS"]
##max_col va a ser siempre lo mismo (ponerlo a mano) y max_row sí que habrá que sacarlo cada vez o guardalo en una variable (maybe mejor sacarlo por memoria)
(max_row, max_col) = tabla.shape
column_settings = []
for header in tabla.columns:
    column_settings.append({'header': header})
worksheet.add_table(0, 0, max_row, max_col - 1, {'columns': column_settings}) 
worksheet.set_column(0, max_col - 1, 12)
writer.close()

### Pruebas de longitudes y accesos

In [9]:
tabla = pd.read_excel('LLM_generated_results.xlsx', index_col=None, sheet_name="RESULTS")

In [10]:
#con esta función sacamos la longitud de las columnas, para poder luego leer la tabla adecuadamente desde otro código
print(len(tabla.index))
print(len(tabla.columns))

1
7

In [11]:
#loc es la fila, que en este caso representa el nivel de machismo de la frase
machismoTier = tabla.loc[len(tabla.index) - 1]
#con at accedemos a la frase creada con el nivel de machismo deseado
machismoTier.iat[0]

np.int64(1)