In [ ]:
#pip install pandas

Requirement already satisfied: pandas in c:\users\jorge\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jorge\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jorge\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jorge\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jorge\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\jorge\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

## Crear un .xlsx con pandas

Gran dilema: cómo guardar mis datos. Es muy importante que decida el formato en el que quiero guardar los datos para poder continuar.

In [13]:
import pandas as pd

NOMBRE_LLM="Llama"

# Crear dataframe con datos
data = ["normal","un poco machista","muy machista"]
df = pd.DataFrame({'Machismo': [0,5,10],
                   'Llama': data,
                   'Microsoft Phi': data})

# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter("frases_creadas_LLMs.xlsx", engine='xlsxwriter')

# Convert the dataframe to an XlsxWriter Excel object. Turn off the default
# header and index and skip one row to allow us to insert a user defined
# header.
df.to_excel(writer, sheet_name= NOMBRE_LLM, startrow=1, startcol=0, header=False, index=False) 

# Get the xlsxwriter workbook and worksheet objects.
workbook = writer.book
worksheet = writer.sheets[NOMBRE_LLM]

# Get the dimensions of the dataframe.
(max_row, max_col) = df.shape

# Create a list of column headers, to use in add_table().
column_settings = []
for header in df.columns:
    column_settings.append({'header': header})

# Add the table.
worksheet.add_table(0, 0, max_row, max_col - 1, {'columns': column_settings}) 

# Make the columns wider for clarity.
worksheet.set_column(0, max_col - 1, 12)

# Close the Pandas Excel writer and output the Excel file.
writer.close()

## Leer un .xlsx con pandas

In [ ]:
tabla = pd.read_excel('frases_creadas_LLMs.xlsx', index_col=None, sheet_name=NOMBRE_LLM)
tabla

   Machismo             Llama     Microsoft Phi
0         0            normal            normal
1         5  un poco machista  un poco machista
2        10      muy machista      muy machista

In [15]:
#con esta función sacamos la longitud de las columnas, para poder luego leer la tabla adecuadamente desde otro código
print(len(tabla.index))
print(len(tabla.columns))

3
3

In [20]:
#loc es la fila, que en este caso representa el nivel de machismo de la frase
machismoScore = tabla.loc[0]
#con at accedemos a la frase creada con el nivel de machismo deseado
machismoScore.iat[1]

'normal'

## Código entero para leer y escribir

In [2]:
NOMBRE_LLM = "Calamar"
SCORE = 7
FRASE = "El calamar está hasta las narices de las tablas de excel."
try:
    open('pruebas_scores.xlsx')
except FileNotFoundError:
    tabla = pd.DataFrame()
else:
    try:
        tabla = pd.read_excel('pruebas_scores.xlsx', index_col=None, sheet_name=NOMBRE_LLM) #como forma alternativa, podemos hacer que index_col=0, y habrá que indexar los locs con los indices en la columna 0
    except ValueError:
        tabla = pd.DataFrame()


if FRASE not in tabla.columns: tabla.insert(len(tabla.columns), FRASE, [(SCORE, "hola"), "Hola"])

writer = pd.ExcelWriter("pruebas_scores.xlsx", engine='xlsxwriter')
tabla.to_excel(writer, sheet_name= NOMBRE_LLM, startrow=1, startcol=0, header=False, index=False)
workbook = writer.book
worksheet = writer.sheets[NOMBRE_LLM]
(max_row, max_col) = tabla.shape
column_settings = []
for header in tabla.columns:
    column_settings.append({'header': header})
worksheet.add_table(0, 0, max_row, max_col - 1, {'columns': column_settings}) 
worksheet.set_column(0, max_col - 1, 12)
writer.close()
tabla

,El calamar está cansadito de las tablas de excel.,El calamar está hasta las narices de las tablas de excel.
0,7,"(7, 'hola')"
1,Hola,Hola